### ISSUE TITLE
piHPSDR dramatic breakage

### ISSUE THREAD

**Issue by madpsy** [pa3gsb/Radioberry-2.x#14]
Just complied the latest version of piHPSDR and it's working perfectly with an HL2.

However, with the radioberry it goes crazy. See attached screenshots showing a pretty rainbow and excessive CPU usage of both pihpsdr and the radioberry user service.

I'm unsure if this is an issue with piHPSDR, how I compiled it or a bug being hit in the radioberry driver. Once this has happened, no other software can use the radioberry (such as SparkSDR) until you run:

1) service radioberry stop
2) rmmod radioberry ; modprobe radioberry
3) service radioberry start

Having to restart the kernel module suggests something is going horribly wrong, somewhere, I'm just not sure where!

I am using the latest stable release of the radioberry driver.

![pihpsdr-2](https://user-images.githubusercontent.com/13963858/134915157-af656255-89f1-40b0-83c6-2a2141f47575.PNG)
![pihpsdr](https://user-images.githubusercontent.com/13963858/134915162-219eb993-7c55-4652-8008-02b5efaa44cd.PNG)

**Comment by madpsy** [comment]
Okay so the issue is PureSignal.

If piHPSDR is compiled with PS support but even if it is **not enabled in piHPSDR** this occurs. I see you disable it in your install script

`sed -i '/^PURESIGNAL_INCLUDE=PURESIGNAL/c\#PURESIGNAL_INCLUDE=PURESIGNAL' ./Makefile;`

I am curious why this breaks radioberry is such a dramatic fassion.

**Comment by pa3gsb** [comment]
please do not use the gpio in pihpsdr

which version of radioberry are you running?

**Comment by madpsy** [comment]
Ah ok - GPIO is the issue, not PureSignal. My bad. I use PS with the HL2 so glad it can be remain there.

I have recompiled with MIDI and PS enabled but GPIO disabled and appears to be working.

I am currently using the beta build of the radioberry driver as I use your pre-amp.

Thanks
