### ISSUE TITLE
pca9555a  and DIY Filter

### ISSUE THREAD

**Issue by ken016** [pa3gsb/Radioberry-2.x#15]
Hello, I would like to build a DIY filter with the help of a pca9555a, unfortunately it is not possible for me (due to a lack of knowledge) to control a suitable board.
FPGA i2c or RPi, which FW. Which program does it work with? Basically, I can read addresses 21 and 20 switchably using tools. I would be grateful for a suitable link :-)
Greetings and many thanks for this cool project.

**Comment by pa3gsb** [comment]
No reaction...
DB2OJ Manfred reported : it is working fine.
