### ISSUE TITLE
Cyclone IV FPGA retarget?

### ISSUE THREAD

**Issue by Doonglaa** [pa3gsb/Radioberry-2.x#16]
In light of the complete absence of Intel Cyclone 10 FPGAs in the current market, I had a look around for alternatives.  I may be able to get my hands on an EP4CE22E22C8N.  Is there any possibility that the gateware could be recompiled for this platform?  *Maybe* even with the same pinout so that the existing board could be used?  I'd love to give your radio a try but the IC shortage doesn't seem to have an end in sight.

I should add that I'm thoroughly impressed with your work on this project and look forward to seeing a working device in the flesh.

Cheers!

**Comment by pa3gsb** [comment]
All the code is open. You can give it a try. Have fun.
