### ISSUE TITLE
Noise floor suddenly becomes very high

### ISSUE THREAD

**Issue by fei666888** [pa3gsb/Radioberry-2.x#17]
When I was using radioberry, a strange issue appeared
When adjusting the frequency quickly, the noise floor suddenly becomes very high.
Use pihpsdr on the raspberry or Powersdr on PC will meet.
It seems that the gain setting has become very high, and the noise floor has covered everything

**Comment by pa3gsb** [comment]
Please use https://github.com/pa3gsb/Radioberry-2.x/releases the dev release.
