### ISSUE TITLE
Soapyradioberry does not support duplex

### ISSUE THREAD

**Issue by paulh002** [pa3gsb/Radioberry-2.x#29]
Hi All,

To support duplex streams soapyradioberry need to be updated, setupStream need to store the streamformat per created stream, now it is a global variable, and cloase stream need to close only the correct stream.
I will propose a change in a pull request is that is ok.

**Comment by pa3gsb** [comment]
Good idea! Looking forward to your improvement.

**Comment by pa3gsb** [comment]
solved by merging pull request.
