### ISSUE TITLE
Radioberry module not loading at startup in bookworm

### ISSUE THREAD

**Issue by keyboarderror** [pa3gsb/Radioberry-2.x#42]
In Raspberry Pi OS Bookworm, the driver installs OK (thank you) but it seems the radioberry module isn't loading when the Pi reboots, and the radioberry does not restart. Adding radioberry to /etc/modules fixes it. So the installation script may need tweaking.

**Comment by seelenreiter** [comment]
@keyboarderror how did you add radioberry to /etc/modules

sorry for beginner questoin

**Comment by keyboarderror** [comment]
You can sudo edit it with vi, nano, or other program like gedit in the wayland gui.
so for example:

sudo nano /etc/modules

Add "radioberry" (no quotes) to the last line. Mine looks like:

i2c-dev
radioberry

Save, exit and reboot.
Hope that helps.
