### ISSUE TITLE
Is my Radioberry working?

### ISSUE THREAD

**Issue by kbeatty** [pa3gsb/Radioberry-2.x#46]
What a cool device!  Thank you and all involved to bring this to the community.

I'm just barely getting into SDR and that may be the entire issue here, but my new Radioberry isn't pulling in anything.  Well, nothing I can actually hear above the noise.  I'm wondering if I could have a bad unit, or it's simply operator error and/or poor antenna choice.  I really don't know what I'm doing, and am having trouble finding the details I need.  I already had the PI 4B, and I just purchased the Radioberry last week at Amazon.

I followed a simple [youtube video](https://www.youtube.com/watch?v=omwT8ItMHyg) and installed the 64 bit Bullseye OS, use the user pi, etc etc.  I had read that the 64 bit OS wasn't working with the Radioberry, but he used it so I decided to give it a try too.  The install was just as describe here.  The good news is that it loaded the Radioberry module without any issues.  modinfo radioberry returns the following:

filename:       /lib/modules/6.1.21-v8+/kernel/drivers/sdr/radioberry.ko
version:        94
license:        GPL
description:    Radioberry SDR device driver. (rpi-4)
author:         Johan Maas - pa3gsb@gmail.com
srcversion:     2A58454FC09C5B8E577A4D1
alias:          of:N*T*Csdr,radioberryC*
alias:          of:N*T*Csdr,radioberry
depends:
name:           radioberry
vermagic:       6.1.21-v8+ SMP preempt mod_unload modversions aarch64

The next step was to install pihpsdr, which also seems to work as advertised.  No errors, both radios give me static and some very faint, just at or below the level of the background noise making it nearly impossible to hear.  This is a strong local AM radio station.  I live in the Kansas City area, so there are plenty of commercial stations, airports, you name it.  I can also use SDRConsole on my Windoze box to access the radio and I get the same results.

The culprit could be the cheap antennas I though would serve me well for an initial test of the system - also off Amazon, two small telescoping antennas 100cm and SMA 50cm.  They both perform similarly.

I'd appreciate any suggestions or advice.  I just need to make a decision as to return it to Amazon for a new one, or just keep working with this one.

**Comment by pa3gsb** [comment]
Please use the forum for questions  https://groups.google.com/g/radioberry

The forum contains a lot of help.

Please provide some pictures to help people to understand the problem you are facing beter.

https://github.com/pa3gsb/Radioberry-2.x/wiki for additional info.
