### ISSUE TITLE
fatal error: fftw3.h: No such file or directory

### ISSUE THREAD

**Issue by reykowski** [pa3gsb/Radioberry-2.x#48]
When I run "make -j$(nproc)" I get: 
fatal error: fftw3.h: No such file or directory

And when I run " sudo make install FPGATYPE=CL016", I get:
fatal error: wdsp.h: No such file or directory

Regards, 

Arne, K4REY

**Comment by pa3gsb** [comment]
Arne

Please use:

https://github.com/pa3gsb/Radioberry-2.x/releases

73 Johan
PA3GSB

**Comment by reykowski** [comment]
Thanks Johan, 
That worked.
73, Arne
