### ISSUE TITLE
Using RPI Secondary Memory Interface?

### ISSUE THREAD

**Issue by rhgndf** [pa3gsb/Radioberry-2.x#50]
Is it possible for a future revision of this to use the Secondary Memory Interface(SMI)? It could support a much wider bandwidth streaming into the RPI.

**Comment by pa3gsb** [comment]
of course it is possible to make use of SMI (some changes in the hw) ; the radioberry is open hw and sw so if you really want SMI i invite you to make a variant.

Beside SMI interface for higher bandwiths ; the radioberry can be connected to a juice board for higher bandwidths; besides higher bandwith the radioberry can be used via usb by a pc running linux or windows.

look at rpi5 and investigate new possibilities and let us know your ideas
