### ISSUE TITLE
Radioberry not holding configuration data

### ISSUE THREAD

**Issue by co6egm** [pa3gsb/Radioberry-2.x#51]
Hello Folks, kind of new here.
I've been experimenting with my radioberry for a few days now and I noticed that the FPGA config file is getting lost when I turn of the raspberry pi, and I have to use console commands to load the config again... As stated in the datasheet, config files have to be uploaded on every start up, but, is there any way to do it automatically or a component that I should add to the board to prevent config from been lost on power off???
I'm sorry if my question seems to be dumb but it's important to me

**Comment by pa3gsb** [comment]
https://groups.google.com/g/radioberry/c/Q_i5JHplacY

the device driver should be started automatically and the device driver is responsible for loading the fpga gateware.
