### ISSUE TITLE
Radioberry won't start after reboot - found solution

### ISSUE THREAD

**Issue by reykowski** [pa3gsb/Radioberry-2.x#52]
Hi Johan,

I installed radioberry on a fresh image for R Pi 4, but the radioberry service would not start up after reboot.
Finally I found out that the config.txt file has been moved from /boot/config.txt to /boot/firmware/config.txt
I added the line "dtoverlay=radioberry" to the end of the new file.
Now everything is working fine.

73,
Arne
K4REY

**Comment by pa3gsb** [comment]
Arne tnx.
