### ISSUE TITLE
Gnuradio companion compatibility ?

### ISSUE THREAD

**Issue by boila1930883** [pa3gsb/Radioberry-2.x#63]
Hi,

Beautiful project ! Thank you for sharing this.

I wanted to know if radioberry is compatible with gnuradio. I looked and did not find a way to use Radioberry with GnuRadio. It says that it is compatible with SoapySDR with Paul's library and that SoapySDR is supported by GnuRadio but I could not find a way to link Radioberry to Gnuradio.

Is it compatible ? If yes, how can I communicate to Radioberry with GnuRadio ?

Many Thanks.

**Comment by pa3gsb** [comment]
See this post : https://groups.google.com/g/radioberry/c/TsQ_nrypdZ0/m/5UbwbLjNAQAJ
