### ISSUE TITLE
    Radioberry-2.x/hardware/hat/release  /beta0.1/

### ISSUE THREAD

**Issue by UT4NJ** [pa3gsb/Radioberry-2.x#66]
Hi! I have received the printed circuit boards for amplifier and I am starting to assemble. I do not understand the presence of relay K301 and the adaptor R301- R303 ?
Please explain to me why not used only one relay as it is made in PA 5w.? thanks!

**Comment by pa3gsb** [comment]
used for pure signal; it is feedback from a sampler in the tx path of your amplifier.

**Comment by UT4NJ** [comment]
Understood, thank you! Another question about L303, L304, on the 130nH scheme and on the 120nH BOM, what nominal setting? Thanks!
